# manual triger 2019-08-22 09:03
language: minimal
env:
  - DIKENZ_VERSION=0.1
#install:
#  - wget ${ACTIVATOR_ZIP_URL}
#  - unzip -q ${ACTIVATOR_ZIP_FILE}
script:
  - env
  - docker build -t myimage .
  - docker run -it myimage rpm -qa
notifications:
  # Email notifications are disabled to not annoy anybody.
  email: false
