# Starter pipeline
- task: Docker@2
  inputs:
    repository: 'letswebmacr'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'


trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    echo "FROM: alpine" > Dockerfile.alpine
    docker build -t letswebmacr.azurecr.io/delme:latest -f Dockerfile.alpine .
    docker login letswebmacr.azurecr.io -u  $ACCESS_TOKEN -p accessToken
    docker push letswebmacr.azurecr.io/delme:latest
    env
  displayName: 'Run a multi-line script'
  env:
    ACCESS_TOKEN: $(accessToken)